services:
  sonarqube:
    image: sonarqube:lts-developer@sha256:1fcbe7c755ff0424b006b3e11dbadd4d93d44b09e16ca3e9fd0c97bbb9adff59
    container_name: sonarqube-server
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      - SONAR_FORCEAUTHENTICATION=false
    networks:
      - sonar-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000"]
      interval: 10s
      timeout: 5s
      retries: 10

networks:
  sonar-network:
    driver: bridge
