services:
  sonarqube:
    image: sonarqube:lts-developer@sha256:b4b4db3a3832506b802aa0ace1f8855bfa5e107b506d88f8f1302243f316d4cd
    container_name: sonarqube-server
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      - SONAR_FORCEAUTHENTICATION=false
    networks:
      - sonar-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000"]
      interval: 10s
      timeout: 5s
      retries: 10

networks:
  sonar-network:
    driver: bridge
