services:
  sonarqube:
    image: sonarqube:lts-developer@sha256:04212809b798768fbd459217765c0f4a51691563603bca6b8317e4a6e8e3024a
    container_name: sonarqube-server
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      - SONAR_FORCEAUTHENTICATION=false
    networks:
      - sonar-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000"]
      interval: 10s
      timeout: 5s
      retries: 10

networks:
  sonar-network:
    driver: bridge
