services:
  sonarqube:
    image: sonarqube:lts-developer@sha256:501ccb4d62ea209500c4dc65a372254b819ebe07cd40b82d0325468d58539581
    container_name: sonarqube-server
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      - SONAR_FORCEAUTHENTICATION=false
    networks:
      - sonar-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000"]
      interval: 10s
      timeout: 5s
      retries: 10

networks:
  sonar-network:
    driver: bridge
