version: "3.9"
services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    environment:
      REACT_APP_BACKEND_URL: http://localhost:17000
      REACT_APP_SOCKET_URL: http://localhost:8008
      REACT_APP_SOCKET_SERVER_PORT: 8008
      REACT_APP_OPEN_WEATHER_RAPID_API_KEY: "9c4b3c4369msh7ff621c01df1d07p1172edjsn74e33213befb"
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - app-network
    volumes:
      - ./frontend/build:/export

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "17000:17000"
    environment:
      MONGODB_URI: "mongodb://mongodb:27018"
      MONGODB_NAME: "ani"
      NODE_ENV: "development"
      PORT: "17000"
      CORS_WHITELIST: "http://localhost:3000,http://localhost:17000,http://server"
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:6.0.4
    container_name: mongodb
    ports:
      - "27018:27018"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=ani
    command: [ "mongod", "--port", "27018" ]
    restart: always
    networks:
      - app-network

  mongo-seed:
    image: mongo:6.0.4
    depends_on:
      - mongodb
    volumes:
      - ./db/mongo/dump:/dump
    entrypoint: [ "sh", "-c", "sleep 5 && mongorestore --host mongodb --port 27018 --db ani /dump/ani" ]
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
