version: "3.9"
services:

  backend:
    container_name: backend
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    container_name: mongodb
    networks:
      - app-network

  nginx:
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - BACKEND_HOST=${BACKEND_HOST:-backend}
      - BACKEND_PORT=${BACKEND_PORT:-17000}

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
