version: "3.9"
services:

  backend:
    image: ${DOCKER_HUB_USERNAME}/forum-backend:${VERSION}
    ports:
      - "17000:17000"
    environment:
      MONGODB_URI: "mongodb://mongodb:27017"
      MONGODB_NAME: "ani"
      NODE_ENV: "development"
      PORT: "17000"
      CORS_WHITELIST: "http://localhost:3000"

  mongodb:
    image: ${DOCKER_HUB_USERNAME}/forum-mongodb:${VERSION}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=ani
    restart: always

  nginx:
    image: ${DOCKER_HUB_USERNAME}/forum-nginx:${VERSION}
    depends_on:
      - backend
    ports:
      - "3000:80"
