#!/bin/bash
set -euo pipefail

cd "$(dirname "$0")/.."

echo "-------------------- ⚒️ Building Sonar Scanner --------------------"
docker build -t sonar-scanner -f sonarqube/Dockerfile.scanner ./sonarqube
