#!/bin/bash
set -euo pipefail

cd "$(dirname "$0")/.."

echo "-------------------- 🐳 Build Docker Images --------------------"

if [[ $# -ne 2 ]]; then
  echo "Usage: $0 <DOCKER_USER> <VERSION>"
  exit 1
fi

DOCKER_USER=$1
VERSION=$2

auto/build-frontend-dev
auto/build-frontend-artifacts

PLATFORMS="linux/amd64,linux/arm64"

# Create and use a builder that supports multi-platform builds
echo "-------------------- 🔧 Setting up Docker Buildx --------------------"
if ! docker buildx ls | grep -q "multiplatform-builder"; then
  docker buildx create --name multiplatform-builder --use
else
  docker buildx use multiplatform-builder
fi

# Build images for multiple platforms
docker buildx build --platform $PLATFORMS --load -f ./backend/Dockerfile.dev -t $DOCKER_USER/forum-backend:$VERSION ./backend &
docker buildx build --platform $PLATFORMS --load -f ./nginx/Dockerfile.dev -t $DOCKER_USER/forum-nginx:$VERSION . &
docker buildx build --platform $PLATFORMS --load -f ./db/mongo/Dockerfile.dev -t $DOCKER_USER/forum-mongodb:$VERSION ./db/mongo &

wait
