#!/bin/bash
set -euo pipefail

cd "$(dirname "$0")/.."

echo "-------------------- 🫡 Launching AniAni --------------------"

export BACKEND_HOST=${BACKEND_HOST:-backend}
export BACKEND_PORT=${BACKEND_PORT:-17000}

if [ "${ENV}" != "test" ]; then
  auto/build-frontend-dev
  auto/build-frontend-artifacts
fi

auto/run-docker-compose
