#!/bin/bash
set -euo pipefail

cd "$(dirname "$0")/.."

echo "-------------------- 🙌 Push Docker Images to ECR --------------------"

DOCKER_USER=$1
VERSION=$2
IS_GITHUB_ACTION=${3:-false}

if [[ "$IS_GITHUB_ACTION" != "true" ]]; then
  echo "-------------------- 🔐 Login AWS Public ECR --------------------"
  aws ecr-public get-login-password --region us-east-1 | \
  docker login --username AWS --password-stdin public.ecr.aws

  echo "-------------------- ⚒️ Building Images --------------------"
  auto/build ${DOCKER_USER} ${VERSION}
else
  echo "-------------------- 📥 Pulling Images from DockerHub --------------------"
  docker pull ${DOCKER_USER}/forum-backend:${VERSION}
  docker pull ${DOCKER_USER}/forum-mongodb:${VERSION}
  docker pull ${DOCKER_USER}/forum-nginx:${VERSION}
fi

echo "-------------------- 🏷️ Tagging Images --------------------"
docker tag ${DOCKER_USER}/forum-backend:${VERSION} public.ecr.aws/g0n3r5g7/comp30022-forum/backend:latest
docker tag ${DOCKER_USER}/forum-mongodb:${VERSION} public.ecr.aws/g0n3r5g7/comp30022-forum/mongodb:latest
docker tag ${DOCKER_USER}/forum-nginx:${VERSION} public.ecr.aws/g0n3r5g7/comp30022-forum/nginx:latest

echo "-------------------- 🚀 Pushing Images to ECR --------------------"
docker push public.ecr.aws/g0n3r5g7/comp30022-forum/backend:latest
docker push public.ecr.aws/g0n3r5g7/comp30022-forum/mongodb:latest
docker push public.ecr.aws/g0n3r5g7/comp30022-forum/nginx:latest
