#!/bin/bash
set -euo pipefail

cd "$(dirname "$0")/.."

echo "-------------------- 🍱 Preparing Environment for E2E Tests --------------------"
auto/launch-app

echo "-------------------- 🧪 Running E2E Tests --------------------"
cd frontend
docker rm -f cypress-e2e || true

# Run tests in sequence: register -> login -> home -> profile
docker run --rm --name cypress-e2e --network=host \
    -v "$(pwd)/cypress/screenshots:/app/cypress/screenshots" \
    -v "$(pwd)/cypress/fixtures:/app/cypress/fixtures" \
    frontend-dev npx cypress run --spec "cypress/e2e/register.cy.js"

docker run --rm --name cypress-e2e --network=host \
    -v "$(pwd)/cypress/screenshots:/app/cypress/screenshots" \
    -v "$(pwd)/cypress/fixtures:/app/cypress/fixtures" \
    frontend-dev npx cypress run --spec "cypress/e2e/login.cy.js"

docker run --rm --name cypress-e2e --network=host \
    -v "$(pwd)/cypress/screenshots:/app/cypress/screenshots" \
    -v "$(pwd)/cypress/fixtures:/app/cypress/fixtures" \
    frontend-dev npx cypress run --spec "cypress/e2e/home.cy.js"

docker run --rm --name cypress-e2e --network=host \
    -v "$(pwd)/cypress/screenshots:/app/cypress/screenshots" \
    -v "$(pwd)/cypress/fixtures:/app/cypress/fixtures" \
    frontend-dev npx cypress run --spec "cypress/e2e/profile.cy.js"
