apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: ryougishiky/forum_server
        ports:
        - containerPort: 8080
        env:
        - name: MYSQL_HOST
          value: mysql.default.svc.cluster.local
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "123456"
        - name: MYSQL_DBNAME
          value: "ani"

---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  type: NodePort
  ports:
    - port: 8080
  selector:
    app: server
