#!/bin/bash
set -euo pipefail

cd "$(dirname "$0")/../.."

echo "-------------------- 🎨 Rendering Docker Compose in GCP --------------------"


docker_compose_params="deploy/docker-compose.test.yml"
docker_compose_template="deploy/docker-compose.temp.yml"
output="rendered-docker-compose.${ENV}.yml"

template=$1
params=$2
output=$3

docker compose -f "${template}" -f "${params}" config > "${output}"

echo "✅ Rendered file saved to ${output}"
