FROM nginx:1.29.0@sha256:3ab4ed065a1437cbbd45e65617b1285bdf6523c6bf56a121e00df41720e09a89

RUN rm /etc/nginx/conf.d/default.conf

COPY ./frontend/build /usr/share/nginx/html

COPY ./nginx/nginx.conf /etc/nginx/nginx.conf

