FROM nginx:1.29.2@sha256:029d4461bd98f124e531380505ceea2072418fdf28752aa73b7b273ba3048903

RUN rm /etc/nginx/conf.d/default.conf

COPY ./frontend/build /usr/share/nginx/html

COPY ./nginx/nginx.conf.template /etc/nginx/templates/default.conf.template
