FROM nginx:1.29.3@sha256:553f64aecdc31b5bf944521731cd70e35da4faed96b2b7548a3d8e2598c52a42

RUN rm /etc/nginx/conf.d/default.conf

COPY ./frontend/build /usr/share/nginx/html

COPY ./nginx/nginx.conf.template /etc/nginx/templates/default.conf.template
