openapi: 3.0.0
info:
  title: User Authentication API
  version: 1.0.0
servers:
  - url: "http://localhost:3000"
paths:
  /users/auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  unique: true
                email:
                  type: string
                  unique: true
                  format: email
                password:
                  type: string
                  format: password
      responses:
        "200":
          description: Successfully registered user
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  email:
                    type: string
                  password:
                    type: string
        "400":
          description: Invalid input

  /users/auth/login:
    post:
      summary: Login a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        "200":
          description: Successfully logged in
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  email:
                    type: string
                  profilePicture:
                    type: string
                  desc:
                    type: string
        "401":
          description: Unauthorized
