name: Build and Tests

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Install Docker Environment
      run: |
        ./auto/install-github-action-env

    - name: Validate Docker Compose configuration
      run: |
        ./auto/validate
        
    - name: Run E2E Tests on Docker Compose
      run: |
        ./auto/run-e2e-tests
      
    - name: Report build result
      if: always()
      run: |
        echo "Docker Compose build completed with status ${{ job.status }}" 
