name: Deploy to GCP VM

on:
  workflow_dispatch:


jobs:
  deploy-gcp-vm:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Read version from version.txt
        id: get_version
        run: ./auto/read-version
