name: Deploy Test Environment to AWS ECS (Fargate Spot)

on:
  push:
    branches:
      - "deploy-app-staging"

jobs:
  bootstrap-iam-role:
    runs-on: ubuntu-22.04
    if: github.event_name == 'workflow_dispatch'
    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS credentials (admin, temporary)
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Terraform Init + Apply (IAM Role only)
      run: |
        cd infra/test/aws
        terraform init
        terraform apply -target=module.github_actions_oidc_role -auto-approve

  deploy-test-app-to-aws-ecs-fargate:
    runs-on: ubuntu-22.04
    needs: bootstrap-iam-role
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS credentials via OIDC
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TERRAFORM_PLAYGROUND_USER }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Terraform Init + Apply (full infra)
      run: |
        cd infra/test/aws
        terraform init
        terraform apply -auto-approve

    - name: Output ALB
      run: |
        cd infra/aws/test
        echo "ALB: $(../.. /auto/run-terraform output -raw alb_dns)"

#    - name: Terraform Destroy
#      if: always()
#      run: |
#        ./auto/run-terraform -chdir=test/aws destroy \
#          -var="project_id=${{ secrets.GCP_PROJECT_ID_STAGING }}" \
#          -var="docker_hub_username=${{ secrets.DOCKER_HUB_USERNAME }}" \
#          -var="docker_hub_password=${{ secrets.DOCKER_HUB_PASSWORD }}" \
#          -var="app_version=${{ steps.get_version.outputs.VERSION }}" \
#          -input=false -auto-approve
