name: Docker Compose Build

# 触发条件：在 main 分支的 PR 被创建、更新或重新打开时
on:
  pull_request:
    
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build with Docker Compose
      run: |
        ./auto/install-github-action-env
        ./auto/build
      env:
        REACT_APP_BACKEND_URL: "http://localhost:5000"
        REACT_APP_SOCKET_URL: "http://localhost:8008"
        REACT_APP_SOCKET_SERVER_PORT: "8008"
        REACT_APP_OPEN_WEATHER_RAPID_API_KEY: ${{ secrets.OPEN_WEATHER_API_KEY || '' }}
        
    - name: Validate Docker Compose configuration
      run: |
        ./auto/validate
        
    - name: Test Docker Compose up
      run: |
        ./auto/health-check
      
    - name: Report build result
      if: always()
      run: |
        echo "Docker Compose build completed with status ${{ job.status }}" 
