name: Publish Docker Images

on:
  workflow_run:
    workflows: ["Build and Tests"]
    types:
      - completed
  push:
#    paths:
#      - version.txt
#    branches:
#      - 'release/**'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Environment
      run: ./auto/install-github-action-env

    - name: Read version from version.txt
      id: get_version
      run: ./auto/read-version

#    - name: Check if tag already exists
#      id: check_tag
#      run: ./auto/check-tag "${{ steps.get_version.outputs.VERSION }}"

    - name: Build Docker image
      run: ./auto/build "${{ secrets.DOCKER_HUB_USERNAME }}" "${{ steps.get_version.outputs.VERSION }}"

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Publish Docker image
      run: ./auto/publish-images "${{ secrets.DOCKER_HUB_USERNAME }}" "${{ steps.get_version.outputs.VERSION }}"
