name: Tests Docker Hub Images

on:
#  workflow_run:
#    workflows: ["Publish Docker Images"]
#    types:
#      - completed
  push:
    branches:
      - 'release/**'

jobs:
  release-test:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Environment
      run: |
        ./auto/install-github-action-env

    - name: Read version from version.txt
      id: get_version
      run: ./auto/read-version

#    - name: Check if tag already exists
#      id: check_tag
#      run: ./auto/check-tag "${{ steps.get_version.outputs.VERSION }}"

    - name: Run E2E Tests with Test Build
      env:
        ENV: "test"
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        VERSION: ${{ steps.get_version.outputs.VERSION }}
      run: |
        ./auto/run-e2e-tests

    - name: Report build result
      if: always()
      run: |
        echo "Docker Compose build completed with status ${{ job.status }}" 
