# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - AniAni

on:
  push:
    branches:
      - ryougi-shiky-azure-1
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_ca32add54703453798b638049e26a920 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a36bb73cf0a14ea798a2cd8f08dec490 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_ca32add54703453798b638049e26a920 }}/ubuntu:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'AniAni'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_88509bb4314b4633aca271608c68ae04 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_ca32add54703453798b638049e26a920 }}/ubuntu:${{ github.sha }}'