name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21'
    - name: Server Build
      run: cd server && go build -v ./...
    - name: Server Unit Test
      run: cd server && go test -v ./...
